#!/bin/bash
##
## EPITECH PROJECT, 2021
## Template folder generator
## Project description:
## folder generator
##

dir=$HOME/.local/share/template_tek/rsrc
pwd=$(pwd)
purple='\033[0;35m'
green='\033[0;32m'

get_name()
{
    echo ${pwd##*/}
}

select_quote()
{
    for ((i = 0; i < $1 ; i++)); do
        read line
    done < $dir/quote.txt
    echo $line
}

gen_c()
{
    cp $dir/header.c $pwd/$1
    sed -ie "s/date/$(date +%Y)/g" $pwd/$1
    sed -ie "s/file/$(get_name)/g" $pwd/$1
    nb=$(shuf -i1-35 -n1)
    sed -ie "s/quote/$(select_quote $nb)/g" $pwd/$1
}

gen_test()
{
    cp $dir/header_test.c $pwd/$1
    sed -ie "s/date/$(date +%Y)/g" $pwd/$1
    sed -ie "s/file/$(get_name)/g" $pwd/$1
    nb=$(shuf -i1-35 -n1)
    sed -ie "s/quote/$(select_quote $nb)/g" $pwd/$1
}

gen_h()
{
    cp $dir/header.h $pwd/$1
    name=$(get_name)
    name="_${name^^}_H_"
    sed -ie"s/date/$(date +%Y)/g" $pwd/$1
    sed -ie "s/name/$(get_name)/g" $pwd/$1
    sed -ie "s/file/${name}/g" $pwd/$1
    nb=$(shuf -i1-35 -n1)
    sed -ie "s/quote/$(select_quote $nb)/g" $pwd/$1
}

gen_makefile()
{
    cp $dir/makefile $pwd/Makefile
    sed -ie "s/date/$(date +%Y)/g" $pwd/Makefile
    sed -ie "s/name/$(get_name)/g" $pwd/Makefile
    nb=$(shuf -i1-35 -n1)
    sed -ie "s/padoru/$(select_quote $nb)/g" $pwd/Makefile
}

main()
{
    if [[ $1 == "-u" ]]; then
        echo "UPDATE"
        (cd $dir/../ && git fetch && git pull)
        (cd $dir/../lib/ && git fetch && git pull)
        exit 0
    fi

    printf "${purple} [+] create folder\n"
    sleep .3
    mkdir -p $pwd/src $pwd/include $pwd/tests $pwd/subject

    printf "${purple} [+] create main.c\n"
    sleep .3
    gen_c src/main.c

    printf "${purple} [+] create tests/tests_$(get_name).c\n"
    sleep .3
    gen_test tests/tests_$(get_name).c

    printf "${purple} [+] create makefile\n"
    sleep .3
    gen_makefile

    printf "${purple} [+] create include/$(get_name).h\n"
    sleep .3
    gen_h include/$(get_name).h

    printf "${purple} [+] create gitignore\n"
    sleep .3
    cat $dir/gitignore | sed "s/name/$(get_name)/g" > $pwd/.gitignore

    printf "${purple} [+] create lib\n"
    sleep .3
    mkdir -p $pwd/lib
    cp -r $dir/../lib/* $pwd/lib/
    rm -rf $pwd/lib/.git

    printf "${green} folder is ready\n"
}

main $1
